### PR TITLE
Feature/date time extensions

### PR DESCRIPTION
**Pull request by baywet**
port of https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/555

### CODE REVIEW

**Comment by baywet** [comment]
CC @MIchaelMainer

**Comment by michael-hawker** [comment]
We should have something like this to get back to DateTimeOffset as well [from my comment on original PR](https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/555#issuecomment-544201473):

```
        public static DateTimeOffset ToDateTimeOffset(this DateTimeTimeZone dttz)
        {
            // https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime
            var datetime = DateTime.Parse(dttz.DateTime);
            var timezone = TimeZoneInfo.FindSystemTimeZoneById(dttz.TimeZone);
            var dto = new DateTimeOffset(datetime, timezone.GetUtcOffset(datetime));

            return dto;
        }
```

@MIchaelMainer would the above be correct approach?  I had to try and reverse engineer it at the time a bit.

**Comment by baywet** [comment]
@michael-hawker let's keep the conversation about what might be missing or not over the original PR. This PR is simply a reflection of the changes.

**Comment by MIchaelMainer** [comment]
Thank you @baywet

**Pull request merged**
