### PR TITLE
Added: PutAsync for PhoneAuthenticationMethodRequest

### PR DESCRIPTION
**Pull request by Bussen**
As PhoneAuthenticationMethodRequest doesn't use PATCH for update, the PUT functionality is implemented as described in the documentation.

https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-update?view=graph-rest-beta&tabs=http

### CODE REVIEW

**Comment by ddyett** [comment]
@zengin @MIchaelMainer is there a generation fix we can do to enable this

**Comment by zengin** [comment]
@ddyett it should be covered by https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/844.

**Comment by ddyett** [comment]
thanks then @andrueastman I think we'll close this PR and validate the root issue here is fixed when we fix https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/844

**Comment by andrueastman** [comment]
@Bussen This is now available through [4.0.1-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/4.0.1-preview) release.
If you are willing to try out the preview package you can check out the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md).
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/e49aa7d374dd749f603fbb84d2d29b3e97e436b1/src/Microsoft.Graph/Generated/requests/PhoneAuthenticationMethodRequest.cs#L148

**Pull request closed without merging**
